version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: microscopio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: microVirtual
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: ["python", "VirtualMicroscope/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DJANGO_DB_HOST: db

  celery:
    build:
      context: .
    command: /app/venv/bin/celery -A VirtualMicroscope worker -l INFO
    volumes:
      - ./VirtualMicroscope:/app
      - ./venv:/app/venv 
    depends_on:
      - web
      - redis 
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0


networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:

