# Generated by Django 2.2.11 on 2023-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='description',
            field=models.TextField(default='nombre', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygon',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
