# Generated by Django 2.2.11 on 2023-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20230722_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='geojson_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
