# Generated by Django 2.2.11 on 2023-07-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0001_initial'),
        ('Projects', '0003_auto_20230722_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='slide',
        ),
        migrations.AlterField(
            model_name='notes',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.ProjectSlide'),
        ),
        migrations.AddField(
            model_name='projectslide',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.Project'),
        ),
        migrations.AddField(
            model_name='projectslide',
            name='slide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Microscopio.Slide'),
        ),
    ]
