# Generated by Django 2.2.11 on 2023-08-04 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0004_auto_20230731_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sharedUsers',
            field=models.ManyToManyField(related_name='proyectos_compartidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
