# Generated by Django 2.2.11 on 2023-08-04 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_project_sharedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sharedUsers',
            field=models.ManyToManyField(blank=True, related_name='proyectos_compartidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
