# Generated by Django 2.2.11 on 2023-08-04 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20230804_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sharedUsers',
            field=models.ManyToManyField(related_name='proyectos_compartidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
