# Generated by Django 2.2.11 on 2023-08-16 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20230804_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sharedUsers',
            field=models.ManyToManyField(related_name='sharedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
