# Generated by Django 2.2.11 on 2023-08-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20230816_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='show',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
