# Generated by Django 2.2.11 on 2023-08-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_notes_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='geojson_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
