# Generated by Django 2.2.11 on 2023-08-20 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0010_auto_20230818_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invitedUsers',
            field=models.ManyToManyField(related_name='invitedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
