# Generated by Django 2.2.11 on 2023-08-21 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_auto_20230821_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
