# Generated by Django 2.2.11 on 2023-08-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0014_auto_20230821_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
