# Generated by Django 4.2.4 on 2023-08-25 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0015_auto_20230821_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adminUsers',
            field=models.ManyToManyField(related_name='adminUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectslide',
            name='adminPermission',
            field=models.BooleanField(default=False),
        ),
    ]
