# Generated by Django 4.2.4 on 2023-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_profile_image.png', upload_to='profile_images/'),
        ),
    ]
