# Generated by Django 2.2.11 on 2023-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('zoomI', models.IntegerField()),
                ('zoomM', models.IntegerField()),
                ('path', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='slides')),
            ],
        ),
    ]
