# Generated by Django 4.2.4 on 2023-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='path',
            field=models.CharField(max_length=50),
        ),
    ]
