# Generated by Django 4.2.4 on 2023-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0002_alter_slide_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='slides'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='zoomI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='zoomM',
            field=models.IntegerField(null=True),
        ),
    ]
