# Generated by Django 4.2.4 on 2023-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0003_alter_slide_image_alter_slide_path_alter_slide_zoomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
