# Generated by Django 4.2.4 on 2023-09-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0004_alter_slide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
