# Generated by Django 4.2.4 on 2023-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0005_alter_slide_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
