# Generated by Django 4.2.4 on 2023-09-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0006_open_slide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Open_Slide',
            new_name='OpenSlide',
        ),
    ]
