# Generated by Django 4.2.4 on 2023-09-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Microscopio', '0007_rename_open_slide_openslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='openslide',
            name='assembled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='assembled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='rawSlide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Microscopio.openslide'),
        ),
    ]
